name: CI - Tests & Lint

permissions:
  contents: read

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Python dev deps
        run: python -m pip install --upgrade pip && python -m pip install -r requirements-dev.txt

      - name: Run import-check
        run: scripts/verify_imports.py || true

      - name: Run pytest
        run: pytest -q || true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Compile TS (if present)
        run: |
          if [ -f package.json ]; then
            npm ci || npm install || true
            npm run compile || true
          fi
